### ISSUE TITLE
Can you please provide a sample running input file and configuration?

### ISSUE THREAD

**Issue by withchencheng** [JSybrandt/ToPMine#2]
Can you please provide a sample running input file and configuration?
```
Warning: This is going to write a logging error, unimportant.
First pass: finding rare words...
Exception in thread "main" java.lang.IllegalStateException: Line #1 does not match regex:
What kind of Visa is required to work in Academia in Japan?
        at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:95)
        at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:44)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
        at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
        at cc.mallet.types.InstanceList.addThruPipe(InstanceList.java:267)
        at DataPreparation.PrepareData.main(PrepareData.java:97)

```

**Comment by hongtaicao** [comment]
> Can you please provide a sample running input file and configuration?
> 
> ```
> Warning: This is going to write a logging error, unimportant.
> First pass: finding rare words...
> Exception in thread "main" java.lang.IllegalStateException: Line #1 does not match regex:
> What kind of Visa is required to work in Academia in Japan?
>         at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:95)
>         at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:44)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:290)
>         at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:282)
>         at cc.mallet.types.InstanceList.addThruPipe(InstanceList.java:267)
>         at DataPreparation.PrepareData.main(PrepareData.java:97)
> ```

A sample dataset should be like the following
```
1 . A Scottish restaurant in a very grand setting in the centre of town. The food is lovely, but it can be a little rich at times, and the service can be a little slow. A good place to take someonne you'd like to impress, though, and it's not ridiculously expensive.
2 . Howies is a local chain with a number of restaurants in Edinburgh, it specialises in modern British/Scottish cuisine and proves itself to be popular with both locals and tourists.
```
